name: CI - Build and Deploy to Firebase

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions deps
        working-directory: functions
        run: npm ci

      - name: Build functions (TypeScript -> lib)
        working-directory: functions
        run: npm run build

      - name: Install web deps
        working-directory: web
        run: npm ci

      - name: Build web
        working-directory: web
        run: npm run build

      - name: Deploy to Firebase (hosting + functions)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: firebase deploy --only hosting,functions --project $FIREBASE_PROJECT_ID
